/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Vista extends javax.swing.JFrame {

    private final DefaultTableModel modelCola;
    private final DefaultTableModel modelAtendidos;
    private final DefaultTableModel modelAcciones;
    private final DefaultTableModel modelEstadisticas;
    private final DefaultTableModel modelBusqueda;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        // Modelo de la cola (NO EDITABLE)
modelCola = new DefaultTableModel(
    new String[]{"ID", "Nombre", "Tipo", "Prioridad", "Hora Entrada"}, 0
){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
tablaCola.setModel(modelCola);

// Modelo de atendidos (NO EDITABLE)
modelAtendidos = new DefaultTableModel(
    new String[]{"ID", "Nombre", "Tipo", "Prioridad", "Entrada", "Salida", "Duración"}, 0
){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
tablaAtendidos.setModel(modelAtendidos);

// Modelo de acciones (NO EDITABLE)
modelAcciones = new DefaultTableModel(
    new String[]{"Acción", "ID Cliente", "Nombre", "Fecha/Hora"}, 0
){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
tablaAcciones.setModel(modelAcciones);

// Modelo de estadísticas (NO EDITABLE)
modelEstadisticas = new DefaultTableModel(
    new String[]{"Métrica", "Valor"}, 0
){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
tablaEstadisticas.setModel(modelEstadisticas);

// Modelo de búsqueda (NO EDITABLE)
modelBusqueda = new DefaultTableModel(
    new String[]{"ID", "Nombre", "Tipo", "Prioridad", "Entrada", "Salida", "Tiempo"}, 0
){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
tablaBusqueda.setModel(modelBusqueda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        comboPrioridad = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCola = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaAtendidos = new javax.swing.JTable();
        btnSalir1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMostrarHistorial = new javax.swing.JButton();
        btnMostrarEstadisticas = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAcciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstadisticas = new javax.swing.JTable();
        btnSalir2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarId = new javax.swing.JTextField();
        btnBuscarId = new javax.swing.JButton();
        btnBuscarSoporte = new javax.swing.JButton();
        btnBuscarMantenimiento = new javax.swing.JButton();
        btnBuscarReclamo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();
        btnMostrarTodos = new javax.swing.JButton();
        btnSalir3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1366, 488, -1, 16));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Coloque su id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 6, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coloque su nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 6, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seleccione su tipo de consulta:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 6, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seleccione la prioridad de la consulta:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 76, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 28, 99, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 28, 89, -1));

        comboTipo.setBackground(new java.awt.Color(25, 118, 210));
        comboTipo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        comboTipo.setForeground(new java.awt.Color(255, 255, 255));
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soporte", "Mantenimiento", "Reclamo" }));
        jPanel1.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 28, -1, -1));

        comboPrioridad.setBackground(new java.awt.Color(25, 118, 210));
        comboPrioridad.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        comboPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Urgente" }));
        jPanel1.add(comboPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 98, 115, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 121, 107));
        btnAgregar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 89, 80, -1));

        btnAtender.setBackground(new java.awt.Color(0, 121, 107));
        btnAtender.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setText("Atender");
        jPanel1.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 90, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 121, 107));
        btnEliminar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 118, 80, -1));

        btnDeshacer.setBackground(new java.awt.Color(255, 0, 51));
        btnDeshacer.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("Deshacer");
        jPanel1.add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, -1));

        tablaCola.setBackground(new java.awt.Color(224, 224, 224));
        tablaCola.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablaCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Prioridad", "Hora Entrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaCola);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 159, 589, 298));

        tablaAtendidos.setBackground(new java.awt.Color(224, 224, 224));
        tablaAtendidos.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablaAtendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Prioridad", "Hora Entrada", "Hora Salida", "Minutos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaAtendidos);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 638, 298));

        btnSalir1.setBackground(new java.awt.Color(183, 28, 28));
        btnSalir1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("Salir");
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 118, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/fondo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 640));

        jTabbedPane1.addTab("Registro", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarHistorial.setBackground(new java.awt.Color(0, 121, 107));
        btnMostrarHistorial.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnMostrarHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarHistorial.setText("Mostrar Historial de acciones");
        jPanel2.add(btnMostrarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 17, 200, -1));

        btnMostrarEstadisticas.setBackground(new java.awt.Color(0, 121, 107));
        btnMostrarEstadisticas.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnMostrarEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarEstadisticas.setText("Mostrar estadisticas");
        jPanel2.add(btnMostrarEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 17, 185, -1));

        btnReiniciar.setBackground(new java.awt.Color(0, 121, 107));
        btnReiniciar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("Reiniciar para un nuevo dia");
        jPanel2.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 67, 200, -1));

        tablaAcciones.setBackground(new java.awt.Color(224, 224, 224));
        tablaAcciones.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablaAcciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acción", "ID Cliente", "Nombre", "Fecha/Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAcciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 560, 309));

        tablaEstadisticas.setBackground(new java.awt.Color(224, 224, 224));
        tablaEstadisticas.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablaEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Métrica", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaEstadisticas);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 600, 309));

        btnSalir2.setBackground(new java.awt.Color(183, 28, 28));
        btnSalir2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnSalir2.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir2.setText("Salir");
        jPanel2.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 67, 185, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/fondo.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 560));

        jTabbedPane1.addTab("Historial y estadisticas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Introduzca ID del cliente a encontrar:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        jPanel3.add(txtBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, -1));

        btnBuscarId.setBackground(new java.awt.Color(0, 121, 107));
        btnBuscarId.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnBuscarId.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarId.setText("Buscar por ID");
        jPanel3.add(btnBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 160, -1));

        btnBuscarSoporte.setBackground(new java.awt.Color(25, 118, 210));
        btnBuscarSoporte.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnBuscarSoporte.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarSoporte.setText("Buscar soporte");
        jPanel3.add(btnBuscarSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 190, -1));

        btnBuscarMantenimiento.setBackground(new java.awt.Color(25, 118, 210));
        btnBuscarMantenimiento.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnBuscarMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMantenimiento.setText("Buscar mantenimiento");
        jPanel3.add(btnBuscarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 190, -1));

        btnBuscarReclamo.setBackground(new java.awt.Color(25, 118, 210));
        btnBuscarReclamo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnBuscarReclamo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReclamo.setText("Buscar los de reclamo");
        btnBuscarReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReclamoActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 160, -1));

        tablaBusqueda.setBackground(new java.awt.Color(224, 224, 224));
        tablaBusqueda.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Prioridad", "Entrada", "Salida", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaBusqueda);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 145, 591, 342));

        btnMostrarTodos.setBackground(new java.awt.Color(0, 121, 107));
        btnMostrarTodos.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnMostrarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodos.setText("Mostrar todos los clientes");
        jPanel3.add(btnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 190, -1));

        btnSalir3.setBackground(new java.awt.Color(183, 28, 28));
        btnSalir3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnSalir3.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir3.setText("Salir");
        jPanel3.add(btnSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/fondo.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 560));

        jTabbedPane1.addTab("Busquedas", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 589));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReclamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarReclamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnBuscarMantenimiento;
    private javax.swing.JButton btnBuscarReclamo;
    private javax.swing.JButton btnBuscarSoporte;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarEstadisticas;
    private javax.swing.JButton btnMostrarHistorial;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btnSalir3;
    private javax.swing.JComboBox<String> comboPrioridad;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaAcciones;
    private javax.swing.JTable tablaAtendidos;
    private javax.swing.JTable tablaBusqueda;
    private javax.swing.JTable tablaCola;
    private javax.swing.JTable tablaEstadisticas;
    private javax.swing.JTextField txtBuscarId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnAtender() {
        return btnAtender;
    }

    public JButton getBtnDeshacer() {
        return btnDeshacer;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnMostrarEstadisticas() {
        return btnMostrarEstadisticas;
    }

    public JButton getBtnMostrarHistorial() {
        return btnMostrarHistorial;
    }

    public JButton getBtnReiniciar() {
        return btnReiniciar;
    }

    public JComboBox<String> getComboPrioridad() {
        return comboPrioridad;
    }

    public JComboBox<String> getComboTipo() {
        return comboTipo;
    }

    public JTable getTablaAcciones() {
        return tablaAcciones;
    }

    public JTable getTablaAtendidos() {
        return tablaAtendidos;
    }

    public JTable getTablaCola() {
        return tablaCola;
    }

    public JTable getTablaEstadisticas() {
        return tablaEstadisticas;
    }

    public DefaultTableModel getModelCola() {
        return modelCola;
    }

    public DefaultTableModel getModelAtendidos() {
        return modelAtendidos;
    }

    public DefaultTableModel getModelAcciones() {
        return modelAcciones;
    }

    public DefaultTableModel getModelEstadisticas() {
        return modelEstadisticas;
    }

    public DefaultTableModel getModelBusqueda() {
        return modelBusqueda;
    }

    public JButton getBtnBuscarId() {
        return btnBuscarId;
    }

    public JButton getBtnBuscarMantenimiento() {
        return btnBuscarMantenimiento;
    }

    public JButton getBtnBuscarReclamo() {
        return btnBuscarReclamo;
    }

    public JButton getBtnBuscarSoporte() {
        return btnBuscarSoporte;
    }

    public JButton getBtnMostrarTodos() {
        return btnMostrarTodos;
    }

    public JButton getBtnSalir1() {
        return btnSalir1;
    }

    public JButton getBtnSalir2() {
        return btnSalir2;
    }

    public JButton getBtnSalir3() {
        return btnSalir3;
    }
    
    public JTable getTablaBusqueda() {
        return tablaBusqueda;
    }

    public JTextField getTxtBuscarId() {
        return txtBuscarId;
    }

    

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

 











}
